name: Unit tests

on:
  - push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: isbang/compose-action@v1.4.1

      - name: Run tests
        run: |
          docker exec phpfpm composer install
          docker exec phpfpm vendor/bin/phpunit